In [1]:
5/2

2.5

In [2]:
import numpy as np

In [ ]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim     # dimension of array

1

In [5]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim

2

In [8]:
print(rev[0][1])   # row 0, column 1
print(rev[0,1])    # same thing

12
12


In [9]:
rev[0,1] = 14
rev

array([[10, 14,  9],
       [15, 11, 13]])

In [10]:
rev.dtype

dtype('int64')

In [11]:
# You can change the dtype explicitly when creating array
rev = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [ ]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [ ]:
# memory size of one element in the array
rev.itemsize

8

In [ ]:
# Size of array (number of elements)
rev.size

6

In [15]:
# total size of array
rev.nbytes

48

In [17]:
# Shape of array ---> no. of rows and columns it consists
rev.shape
#  2 rows 3 column

(2, 3)

In [21]:
# sort array (default - asc)
print(np.sort(rev))


[[ 9. 10. 12.]
 [11. 13. 15.]]


In [22]:
np.sort(rev,axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [23]:
# zero array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# create array in range (end number not included ie,20)
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# array in range with step size 2.
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
# array with lineraly/evenly spaced numbers
np.linspace(10,20) 
# include both start and end number
# by default 50 elements

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [29]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [33]:
# to convert multi-dim array to 1-dim array
print(rev.ravel())   
print(rev)
# it returns a view (linked to original array)
# changes may affect original copy

a = np.array([1,2,3,4])
x = a.ravel()
x[0] = 20
print(a)

[10. 12.  9. 15. 11. 13.]
[[10. 12.  9.]
 [15. 11. 13.]]
[20  2  3  4]


In [36]:
print(rev.flatten())
print(rev)

# it returns a copy
# changes do not affect the original array

a = np.array([1,2,3,4])
x = a.flatten()
x[0] = 10
print(a)

[10. 12.  9. 15. 11. 13.]
[[10. 12.  9.]
 [15. 11. 13.]]
[1 2 3 4]


In [38]:
# To change shape of array
rev.reshape(3,2)

# the new shape must be compatible with the older one.
# ie, the number of elements must be same before and after reshaping

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [39]:
rev.reshape(1,6)

array([[10., 12.,  9., 15., 11., 13.]])

In [40]:
rev.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [41]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [43]:
rev.min()

np.float64(9.0)

In [44]:
rev.max()

np.float64(15.0)

In [45]:
# sum
rev.sum(axis=1)   # row addition

array([31., 39.])

In [ ]:
rev.sum()    # sum all

np.float64(70.0)

In [ ]:
rev.sum(axis=0)    # column addition

array([25., 23., 22.])

In [49]:
# to iterate
for row in rev:
    print("row:->",row)

row:-> [10. 12.  9.]
row:-> [15. 11. 13.]


In [50]:
b = np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [52]:
np.square(b)

array([  1,  16, 256])