In [1]:
5/2

2.5

In [2]:
import numpy as np

In [4]:
# sales data for Quarter 1 (Martix 1)
# Rows represent different products, columns represent different regions

q1 = np.array([
        [200,220,250],       # porduct a
        [150,180,210],       # product b
        [300,330,360]        # product c
    ])

# sales data for Quarter 2 (Matrix 2)
q2 = np.array([
        [209,231,259],       # product a
        [155,192,222],       # product b
        [310,340,375]        # product c
])

In [5]:
# total sales in both quarter
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [6]:
# sales relation in quarter
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [7]:
# percentage increase
(q2 -q1)*100 / q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [8]:
# prices for different products in different region
prices = np.array([
    [10,12,11],
    [8,9,10],
    [15,16,17]
])

q1_revenue = q1 * prices 
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [10]:
q1_discount = q1_revenue * 0.2 # discount of 20% 
q1_discount

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [11]:
net_revenue = q1_revenue - q1_discount
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [12]:
# dot product (mostly used in ml)

features = np.array([
    [2000,3],    # house 1
    [1800,2]     # house 2
])

weights = np.array([150,50000])

# to predict the price of the house you do 
# 2000*150 + 3*50000

price = np.dot(features,weights)
price

array([450000, 370000])

In [13]:
2000*150 + 3*50000

450000

In [15]:
# cross product
c = np.array([1,2,3])
d = np.array([4,5,6])

np.cross(d,c)

array([ 3, -6,  3])