In [3]:
# NUMPY 
# python library used for:
# 1) fast mathematical operations
# 2) working with arrays and matrices
# 3) numerical computing

# Why Numpy Arrays better than Lists?
# Numpy arrays are:
# 1) faster  2) Use less memory  3) Support Vectorized operations

# Vectorization?
# performing operations on entire arrays at once instead of using loops manually.

# vectorized operation are :
# 1) Faster  2) Shorter  3) Cleaner
# because Numpy internally uses optimized low-level code.

In [1]:
# To install numpy package
! pip install numpy

In [2]:
# To check all packages installed
! pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
beautifulsoup4          4.14.3
bs4                     0.0.2
certifi                 2026.5.20
charset-normalizer      3.4.7
colorama                0.4.6
comm                    0.2.3
debugpy                 1.8.20
decorator               5.3.1
executing               2.2.1
idna                    3.15
ipykernel               7.2.0
ipython                 9.13.0
ipython_pygments_lexers 1.1.1
jedi                    0.20.0
jupyter_client          8.8.0
jupyter_core            5.9.1
matplotlib-inline       0.2.2
nest-asyncio            1.6.0
numpy                   2.4.6
packaging               26.2
parso                   0.8.7
pip                     26.1.1
platformdirs            4.9.6
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                2.20.0
python-dateutil         2.9.0.post0
pyzmq                   27.1.0
requests        

In [3]:
# To check if numpy is installed
! pip show numpy

Name: numpy
Version: 2.4.6
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages
Requires: 
Required-by: 


In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
list_ = [1,2,3]
list_

[1, 2, 3]

In [8]:
# arrays occupy less memory than list 
python_list = list(range(10))
python_list[:5]

[0, 1, 2, 3, 4]

In [9]:
import sys
sys.getsizeof(python_list)

136

In [10]:
python_array = np.array(range(10))
python_array[:5]

# Why NumPy Array May Show Bigger Size Initially?
# NumPy arrays have extra internal metadata like:
# datatype info
# shape
# strides
# buffer management
# So for very small arrays (like 10 elements):
# this overhead can make NumPy appear larger.


array([0, 1, 2, 3, 4])

In [11]:
sys.getsizeof(python_array)

# But For Large Data…
# NumPy becomes much more memory efficient.
# Example:
# 1 million integers
# Python list becomes huge because:
# each integer is a separate Python object
# NumPy array stores:
# raw integers compactly
# Huge difference appears.

192

In [ ]:
python_array.nbytes

80

In [15]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = zip(l1,l2)
for i in l3:
    print(i)

# or 
for x,y in zip(l1,l2):
    print(x,y)

(1, 4)
(2, 5)
(3, 6)
1 4
2 5
3 6


In [ ]:
# arrays are much faster than lists.
import time 

SIZE = 1000
l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()

print(f"Python list took : {end_time - start_time} time to execute.")

Python list took : 0.00021982192993164062 time to execute.


In [17]:
n1 = np.array(SIZE)
n2 = np.array(SIZE)

start_time = time.time()
n3 = n1 + n2
end_time = time.time()

print(f"Python Numpy array took : {end_time - start_time} time to execute.")

Python Numpy array took : 0.00010585784912109375 time to execute.


In [21]:
# Convinient use with built in fuctions
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 + l2)   # performs concatenation

# for addition 
l3 = []
for x,y in zip(l1,l2):
    l3.append(x+y)
print(l3)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [22]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n1 += n2
print(n1)

[5 7 9]
