In [1]:
5/2

2.5

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# does not include end
a[0:2]

array([1, 2])

In [ ]:
# index till last
a[2:]

array([3, 4, 5, 6])

In [7]:
# last element
a[-1]

np.int64(6)

In [ ]:
# second last 
a[-2]

np.int64(5)

In [ ]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b[1,2]

np.int64(6)

In [15]:
b[-1]

array([7, 8, 9])

In [17]:
b[-3,0:2]

array([1, 2])

In [18]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [19]:
b[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# row 2, then from column 1 onwards
b[2,1:]

array([8, 9])

In [27]:
# Customer id, name
c = np.array([
    [101,"amrendra"],
    [102,"mahendra"],
    [103,"devasena"]
])

# id, purchase amount, date
d = np.array([
    [101,250.50,'2026-08-01'],
    [102,10,'2026-08-24'],
    [103,23,'2026-08-02']
])

In [ ]:
# combine all the info --> horizontally
comb = np.hstack((c,d))
comb

array([['101', 'amrendra', '101', '250.5', '2026-08-01'],
       ['102', 'mahendra', '102', '10', '2026-08-24'],
       ['103', 'devasena', '103', '23', '2026-08-02']], dtype='<U32')

In [30]:
# combines all the info --> vertically
e = np.array([
    [104,'shivagami'],
    [105,'kattappa'],
    [106,'bhallaldeva']
])

comb_e = np.vstack((c,e))
comb_e

array([['101', 'amrendra'],
       ['102', 'mahendra'],
       ['103', 'devasena'],
       ['104', 'shivagami'],
       ['105', 'kattappa'],
       ['106', 'bhallaldeva']], dtype='<U21')

In [7]:
# Spliting the array into 2
transactions = np.array([
    [101,'joey',10.33,'2018-09-08'],
    [102,'rachel',500.34,'2020-09-03'],
    [103,'monica',900.98,'2020-11-20'],
    [104,'phoebe',178.9,'2020-10-5']
])

In [ ]:
# horizontal split
code , date = np.hsplit(transactions,[3])
code , date

(array([['101', 'joey', '10.33'],
        ['102', 'rachel', '500.34'],
        ['103', 'monica', '900.98'],
        ['104', 'phoebe', '178.9']], dtype='<U32'),
 array([['2018-09-08'],
        ['2020-09-03'],
        ['2020-11-20'],
        ['2020-10-5']], dtype='<U32'))

In [34]:
# vertical split
x , y = np.vsplit(transactions, [3])
x , y

(array([['101', 'joey', '10.33', '2018-09-08'],
        ['102', 'rachel', '500.34', '2020-09-03'],
        ['103', 'monica', '900.98', '2020-11-20']], dtype='<U32'),
 array([['104', 'phoebe', '178.9', '2020-10-5']], dtype='<U32'))

In [3]:
monthly_sales = np.array([30,33,35,28,42])
results =  monthly_sales < 32
monthly_sales[results]

array([30, 28])

In [4]:
np.max(monthly_sales)

np.int64(42)

In [5]:
a = np.argmax(monthly_sales)
a

np.int64(4)

In [6]:
monthly_sales[a]

np.int64(42)

In [11]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[:2,1:])

[[20 30]
 [50 60]]
